### ISSUE TITLE
Often need to reload the page before playing a video

### ISSUE THREAD

**Issue by ByJumperX4** [user234683/youtube-local#101]
```
Traceback (most recent call last):
  File "/home/byjumperx4/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/byjumperx4/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/byjumperx4/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/home/byjumperx4/.local/lib/python3.8/site-packages/gevent/_ssl3.py", line 567, in recv_into
    return self.read(nbytes, buffer)
  File "/home/byjumperx4/.local/lib/python3.8/site-packages/gevent/_ssl3.py", line 385, in read
    return self._sslobj.read(nbytes, buffer)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/byjumperx4/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/byjumperx4/.local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/byjumperx4/.local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/byjumperx4/.local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/home/byjumperx4/youtube-local/youtube/watch.py", line 543, in get_watch_page
    util.check_gevent_exceptions(tasks[1])
  File "/usr/home/byjumperx4/youtube-local/youtube/util.py", line 590, in check_gevent_exceptions
    raise task.exception
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/home/byjumperx4/youtube-local/youtube/watch.py", line 386, in extract_info
    player_response = util.fetch_url(
  File "/usr/home/byjumperx4/youtube-local/youtube/util.py", line 300, in fetch_url
    response, cleanup_func = fetch_url_response(
  File "/usr/home/byjumperx4/youtube-local/youtube/util.py", line 270, in fetch_url_response
    response = pool.request(method, url, headers=headers, body=data,
  File "/home/byjumperx4/.local/lib/python3.8/site-packages/urllib3/request.py", line 78, in request
    return self.request_encode_body(
  File "/home/byjumperx4/.local/lib/python3.8/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/byjumperx4/.local/lib/python3.8/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/byjumperx4/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/byjumperx4/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/byjumperx4/.local/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/home/byjumperx4/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/byjumperx4/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/byjumperx4/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/home/byjumperx4/.local/lib/python3.8/site-packages/gevent/_ssl3.py", line 567, in recv_into
    return self.read(nbytes, buffer)
  File "/home/byjumperx4/.local/lib/python3.8/site-packages/gevent/_ssl3.py", line 385, in read
    return self._sslobj.read(nbytes, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
```

I'm often getting an error like this one from urllib3 saying that the connection has been reset by peer. I need to reload the page 1 or 2 times and I can play the video. (I have a pretty bad internet connection).
Running on FreeBSD 13-RELEASE but also happens on GNU/Linux.

**Comment by user234683** [comment]
Is this still an issue? Feel free to reopen if so. Seems urllib3 ought to retry by default, but maybe it isn't in this case since it's not raising a MaxRetryError, but I'm not sure:
![image](https://github.com/user234683/youtube-local/assets/28744867/53ee4bfe-a146-4a69-ac33-f1c000d39679)
