### ISSUE TITLE
Viewing Page 2 of any playlist throws up a 500 Uncaught exception

### ISSUE THREAD

**Issue by arnoldsecret** [user234683/youtube-local#102]
```
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Gateway-2000\apps\browser\youtube-local\python\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\Desktop\Gateway-2000\apps\browser\youtube-local\python\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\Desktop\Gateway-2000\apps\browser\youtube-local\python\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\Desktop\Gateway-2000\apps\browser\youtube-local\python\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\User\Desktop\Gateway-2000\apps\browser\youtube-local\youtube\channel.py", line 315, in get_channel_page
    return get_channel_page_general_url('https://www.youtube.com/channel/' + channel_id, tab, request, channel_id)
  File "C:\Users\User\Desktop\Gateway-2000\apps\browser\youtube-local\youtube\channel.py", line 279, in get_channel_page_general_url
    'playlists', view)
  File "C:\Users\User\Desktop\Gateway-2000\apps\browser\youtube-local\youtube\channel.py", line 141, in get_channel_tab
    data=json.dumps(data), debug_name='channel_tab', report_text=message)
  File "C:\Users\User\Desktop\Gateway-2000\apps\browser\youtube-local\youtube\util.py", line 348, in fetch_url
    ip=None)
youtube.util.FetchError: HTTP error during request: 500 Internal Server Error

```

**Comment by user234683** [comment]
Working on my end. Is there a specific channel that demonstrates the issue? It appears YouTube is returning the 500 error; could have been a temporary glitch on their end

**Comment by arnoldsecret** [comment]
https://www.youtube.com/channel/UC0wNSTMWIL3qaorLx0jie6A (Ani-One Asia)
https://www.youtube.com/channel/UCGbshtvS9t-8CW11W7TooQg (Muse Asia)
both region-locked to Asian territories, I think that might be the issue.

**Comment by user234683** [comment]
I only see one page of playlists on those channels though

**Comment by arnoldsecret** [comment]
like there's no Next Page button of some kind in the bottom of the page? I have it on my end.
![Untitled](https://user-images.githubusercontent.com/41223243/143792208-e7b8ba08-da9a-4db4-85fc-e3ff51c9cbfa.png)

**Comment by user234683** [comment]
![image](https://user-images.githubusercontent.com/28744867/143796542-6ab8c9c3-a301-4a79-8a2b-edc0b0278f49.png)
Right. Are you using the latest version? Is Tor routing enabled/disabled? If disabled, what region are you in? I tried changing region to jp and tw in Tor settings but didn't notice a difference.

**Comment by arnoldsecret** [comment]
PH

**Comment by raelb** [comment]
Happens for me with this channel:
https://www.youtube.com/channel/UC4a-Gbdw7vOaccHmFo40b9g
Khan Academy

Don't know if this is a region locked channel. Think it might have to do with the fact that they have playlist categories.

Not using Tor.

Traceback (most recent call last):
  File "C:\Downloads\YouTube\Servers\youtube-local-v2.7.2-windows\youtube-local\python\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Downloads\YouTube\Servers\youtube-local-v2.7.2-windows\youtube-local\python\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Downloads\YouTube\Servers\youtube-local-v2.7.2-windows\youtube-local\python\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Downloads\YouTube\Servers\youtube-local-v2.7.2-windows\youtube-local\python\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Downloads\YouTube\Servers\youtube-local-v2.7.2-windows\youtube-local\youtube\channel.py", line 329, in get_channel_page
    return get_channel_page_general_url('https://www.youtube.com/channel/' + channel_id, tab, request, channel_id)
  File "C:\Downloads\YouTube\Servers\youtube-local-v2.7.2-windows\youtube-local\youtube\channel.py", line 291, in get_channel_page_general_url
    polymer_json = get_channel_tab(channel_id, page_number, sort,
  File "C:\Downloads\YouTube\Servers\youtube-local-v2.7.2-windows\youtube-local\youtube\channel.py", line 144, in get_channel_tab
    content = util.fetch_url(
  File "C:\Downloads\YouTube\Servers\youtube-local-v2.7.2-windows\youtube-local\youtube\util.py", line 365, in fetch_url
    raise FetchError(str(response.status), reason=response.reason,
youtube.util.FetchError: HTTP error during request: 500 Internal Server Error
