### ISSUE TITLE
Error 500 when hitting Next Page on a youtube channel's Playlists tab

### ISSUE THREAD

**Issue by madoptics** [user234683/youtube-local#182]
Traceback (most recent call last):
  File "D:\-\youtube-local-v2.8.5-windows\python\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\-\youtube-local-v2.8.5-windows\python\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\-\youtube-local-v2.8.5-windows\python\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\-\youtube-local-v2.8.5-windows\python\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\-\youtube-local-v2.8.5-windows\youtube\channel.py", line 537, in get_channel_page
    return get_channel_page_general_url('https://www.youtube.com/channel/' + channel_id, tab, request, channel_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\-\youtube-local-v2.8.5-windows\youtube\channel.py", line 469, in get_channel_page_general_url
    polymer_json = get_channel_tab(channel_id, page_number, sort,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\-\youtube-local-v2.8.5-windows\youtube\channel.py", line 236, in get_channel_tab
    content = util.fetch_url(
              ^^^^^^^^^^^^^^^
  File "D:\-\youtube-local-v2.8.5-windows\youtube\util.py", line 359, in fetch_url
    raise FetchError(str(response.status), reason=response.reason,
youtube.util.FetchError: HTTP error during request: 500 Internal Server Error

**Comment by Vjay15** [comment]
the same problem but w every channel
