### ISSUE TITLE
"Sort by oldest" - 500 Uncaught Exception

### ISSUE THREAD

**Issue by stl3** [user234683/youtube-local#188]
```
Traceback (most recent call last):
  File "F:\Programming\GitHub\youtube-local\python\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Programming\GitHub\youtube-local\python\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Programming\GitHub\youtube-local\python\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Programming\GitHub\youtube-local\python\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Programming\GitHub\youtube-local\youtube\channel.py", line 537, in get_channel_page
    return get_channel_page_general_url('https://www.youtube.com/channel/' + channel_id, tab, request, channel_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Programming\GitHub\youtube-local\youtube\channel.py", line 461, in get_channel_page_general_url
    util.check_gevent_exceptions(*tasks)
  File "F:\Programming\GitHub\youtube-local\youtube\util.py", line 602, in check_gevent_exceptions
    raise task.exception
  File "src\\gevent\\greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "F:\Programming\GitHub\youtube-local\youtube\channel.py", line 236, in get_channel_tab
    content = util.fetch_url(
              ^^^^^^^^^^^^^^^
  File "F:\Programming\GitHub\youtube-local\youtube\util.py", line 359, in fetch_url
    raise FetchError(str(response.status), reason=response.reason,
youtube.util.FetchError: HTTP error during request: 500 Internal Server Error
```

**Comment by a-arbabian** [comment]
Same with "Sort by views"!
