### ISSUE TITLE
500 Uncaught exception: unable to play any video

### ISSUE THREAD

**Issue by pineapples5972** [user234683/youtube-local#203]
500 Uncaught exception:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/youtube/watch.py", line 665, in get_watch_page
    util.check_gevent_exceptions(tasks[1])
  File "/app/youtube/util.py", line 602, in check_gevent_exceptions
    raise task.exception
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/app/youtube/watch.py", line 442, in extract_info
    util.check_gevent_exceptions(*tasks)
  File "/app/youtube/util.py", line 602, in check_gevent_exceptions
    raise task.exception
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/app/youtube/watch.py", line 397, in fetch_player_response
    player_response = util.fetch_url(
  File "/app/youtube/util.py", line 359, in fetch_url
    raise FetchError(str(response.status), reason=response.reason,
youtube.util.FetchError: HTTP error during request: 400 Bad Request
```

**Comment by pineapples5972** [comment]
Fixed it by updating to newer version.
