### ISSUE TITLE
Youtube-local doesn't work for some videos, mainly music videos

### ISSUE THREAD

**Issue by tenextractor** [user234683/youtube-local#218]
Trying to open https://www.youtube.com/watch?v=kJQP7kiw5Fk for example, gives this error:

```
Traceback (most recent call last):
  File "...youtube-local/venv/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...youtube-local/venv/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...youtube-local/venv/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "...youtube-local/venv/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...youtube-local/youtube/watch.py", line 647, in get_watch_page
    url = info['formats'][0]['url']
          ~~~~~~~~~~~~~~~^^^
IndexError: list index out of range```

**Comment by alive4ever** [comment]
Hi, I encountered similar problem and prepared a few changes in the `feature-innertube-client-fix` branch of [my fork](/alive4ever/youtube-local)

Let me know if my changes solve this issue.

**Comment by tenextractor** [comment]
@alive4ever Yes, your changes solved it. Thanks.

**Comment by nakrosrex** [comment]
> Hi, I encountered similar problem and prepared a few changes in the `feature-innertube-client-fix` branch of [my fork](/alive4ever/youtube-local)
> 
> Let me know if my changes solve this issue.

Hey thanks for this the problem has been solved by using your changes can you please resolve the playlist issue described here #220

**Comment by arborealoctopus** [comment]
another confirmation your changes solve the music vid problem, thank you very much.

for those on windows who are building themselves, note that fake-useragent (a new dependency introduced in this fix) doesn't seem to work properly with how this tool is built. In the `fake-useragent` file `settings.py` it returns `importlib.metadata.PackageNotFoundError` which seems to be a result of not "properly" installing the package (tbh I don't know how the build system works on this project, so "proper" may be the wrong word). I poked around a little bit but couldn't figure out how to fix this, so I ended up just hard-coding the addon version as a constant (settings.py line 7). Works great now. 

thanks again

**Comment by arborealoctopus** [comment]
Oh, I'm silly, I should have looked at the dist generator...its probably this: 
![image](https://github.com/user-attachments/assets/bd50cd25-0022-4ccf-b67c-00e1493c2004)

**Comment by alive4ever** [comment]
Hi, sorry for the inconvenience. I don't test the `generate_release.py` script since I just run the web app manually on Debian.

```sh
python3.11 -m venv --upgrade-deps venv
pip install -r requirements.txt
source ./venv/bin/activate
python ./server.py
```

Currently doing a trial build to run `generate_release.py` via github action to find out if a release is possible with my proposed changes.

As for playlist page problem, I don't have a clue since I am focusing on the watch page, especially player extraction from yt-api response.

**Comment by alive4ever** [comment]
> confirmed, removing these lines makes a functional build ✅

Hi, after several attempts of github actions, a release is possible without those changes (winehq stable, python 3.11.9). Look at releases section of [my repo](/alive4ever/youtube-local)

The only required change is modifying branch name from `master` to `HEAD`

```patch
diff --git a/generate_release.py b/generate_release.py
index aed9d22..36d368b 100644
--- a/generate_release.py
+++ b/generate_release.py
@@ -92,7 +92,7 @@ if os.path.exists('./youtube-local'):
 # confused with working directory. I'm calling it the same thing so it will
 # have that name when extracted from the final release zip archive)
 log('Making copy of youtube-local files')
-check(os.system('git archive --format tar master | 7z x -si -ttar -oyoutube-local'))
+check(os.system('git archive --format tar HEAD | 7z x -si -ttar -oyoutube-local'))

 if len(os.listdir('./youtube-local')) == 0:
     raise Exception('Failed to copy youtube-local files')
```

**Comment by alive4ever** [comment]
> confirmed, removing these lines makes a functional build ✅

So I tested my own github action build and found that the issue is during runtime, not during build. Sorry for my ignorance in the previous reply.

I've added a commit in my pull-request to modify `generate_release.py` to not remove dist-info files so `fake-useragent` module can start.

```patch
commit 5276825431b3501b5fcbd0b0ecf93a19414c7f09
Author: alive4ever <alive4ever@users.noreply.github.com>
Date:   Tue Nov 5 14:59:44 2024 +0000

    generate_release: avoid removing dist-info dirs
    
    Avoid removing dist-info directories so fake-useragent can start, since
    the module will call importlib.metadata on init.
    
    Also use HEAD instead of master during archive copying step to allow
    generate_release.py to run on branch other than master.

diff --git a/generate_release.py b/generate_release.py
index aed9d22..37512da 100644
--- a/generate_release.py
+++ b/generate_release.py
@@ -92,7 +92,7 @@ if os.path.exists('./youtube-local'):
 # confused with working directory. I'm calling it the same thing so it will
 # have that name when extracted from the final release zip archive)
 log('Making copy of youtube-local files')
-check(os.system('git archive --format tar master | 7z x -si -ttar -oyoutube-local'))
+check(os.system('git archive --format tar HEAD | 7z x -si -ttar -oyoutube-local'))
 
 if len(os.listdir('./youtube-local')) == 0:
     raise Exception('Failed to copy youtube-local files')
@@ -217,10 +217,10 @@ wine_run(['./python/python.exe', '-I', '-m', 'pip', 'uninstall', '--yes', 'pip',
 log('Removing pyc files')   # Have to do this because get-pip and some packages don't respect --no-compile
 remove_files_with_extensions(r'./python', ['.pyc'])
 
-log('Removing dist-info and __pycache__')
+log('Removing __pycache__')
 for root, dirs, files in os.walk(r'./python'):
     for dir in dirs:
-        if dir == '__pycache__' or dir.endswith('.dist-info'):
+        if dir == '__pycache__':
             shutil.rmtree(os.path.join(root, dir))
 
```
