### ISSUE TITLE
I can't change page on some channels

### ISSUE THREAD

**Issue by arankaren** [user234683/youtube-local#54]
Whenever I try to change pages in a channel, show me an error a `500 Uncaught exception`

Steps to reproduce:

- Go to any channel ([Here's an example](https://www.youtube.com/channel/UCXuqSBlHAE6Xw-yeJA0Tunw/videos))
- Click on the replies of any comment

youtube-local version: 2.5.4
OS: Debian Buster

Traceback
```
Traceback (most recent call last):
File "/home/liberate/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app response = self.full_dispatch_request()
File "/home/liberate/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request rv = self.handle_user_exception(e)
File "/home/liberate/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception reraise(exc_type, exc_value, tb)
File "/home/liberate/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise raise value
File "/home/liberate/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request rv = self.dispatch_request()
File "/home/liberate/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args)
File "/home/liberate/youtube/channel.py", line 273, in get_channel_page return get_channel_page_general_url('https://www.youtube.com/channel/' + channel_id, tab, request, channel_id)
File "/home/liberate/youtube/channel.py", line 224, in get_channel_page_general_url util.check_gevent_exceptions(*tasks)
File "/home/liberate/youtube/util.py", line 542, in check_gevent_exceptions raise task.exception
File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
File "/home/liberate/youtube/channel.py", line 127, in get_channel_tab debug_name='channel_tab', report_text=message)
File "/home/liberate/youtube/util.py", line 318, in fetch_url ip=None) youtube.util.FetchError: HTTP error during request: 500 Internal Server Error 
```

**Comment by user234683** [comment]
It seems they've changed the API being used. I expect the API endpoint we're using may be disabled soon, making it impossible to do arbitrary page requests unless I can find an API YouTube developers forgot to close up. However, it is claimed [here](https://github.com/iv-org/invidious/issues/1814) that this issue is on YouTube's end. I'll fix the issue for the first page of channels and wait and see whether this issue goes away for other pages
