### ISSUE TITLE
Failed to establish a new connection: [Errno 10061] [WinError 10061]

### ISSUE THREAD

**Issue by Ln6r** [user234683/youtube-local#69]
Hello,

I just wanted to use youtube-local, but when I open the http://localhost:8080/[youtube-link] - link in the Tor-Browser it says that the connection failed to the localhost. When I open the link in another browser this pops up:

Traceback (most recent call last):
  File "D:\Videos\youtube-local-v2.5.8-windows\youtube-local\python\lib\site-packages\socks.py", line 787, in connect
    super(socksocket, self).connect(proxy_addr)
  File "D:\Videos\youtube-local-v2.5.8-windows\youtube-local\python\lib\site-packages\gevent\_socketcommon.py", line 607, in connect
    raise _SocketError(err, strerror(err))
ConnectionRefusedError: [Errno 10061] [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Videos\youtube-local-v2.5.8-windows\youtube-local\python\lib\site-packages\urllib3\contrib\socks.py", line 105, in _new_conn
    **extra_kw
  File "D:\Videos\youtube-local-v2.5.8-windows\youtube-local\python\lib\site-packages\socks.py", line 209, in create_connection
    raise err
  File "D:\Videos\youtube-local-v2.5.8-windows\youtube-local\python\lib\site-packages\socks.py", line 199, in create_connection
    sock.connect((remote_host, remote_port))
  File "D:\Videos\youtube-local-v2.5.8-windows\youtube-local\python\lib\site-packages\socks.py", line 47, in wrapper
    return function(*args, **kwargs)
  File "D:\Videos\youtube-local-v2.5.8-windows\youtube-local\python\lib\site-packages\socks.py", line 800, in connect
    raise ProxyConnectionError(msg, error)
socks.ProxyConnectionError: Error connecting to SOCKS5 proxy 127.0.0.1:9150: [Errno 10061] [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Videos\youtube-local-v2.5.8-windows\youtube-local\python\lib\site-packages\urllib3\connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "D:\Videos\youtube-local-v2.5.8-windows\youtube-local\python\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "D:\Videos\youtube-local-v2.5.8-windows\youtube-local\python\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "D:\Videos\youtube-local-v2.5.8-windows\youtube-local\python\lib\site-packages\urllib3\connection.py", line 353, in connect
    conn = self._new_conn()
  File "D:\Videos\youtube-local-v2.5.8-windows\youtube-local\python\lib\site-packages\urllib3\contrib\socks.py", line 128, in _new_conn
    self, "Failed to establish a new connection: %s" % error
urllib3.exceptions.NewConnectionError: <urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x04DABEF0>: Failed to establish a new connection: [Errno 10061] [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Videos\youtube-local-v2.5.8-windows\youtube-local\python\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Videos\youtube-local-v2.5.8-windows\youtube-local\python\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Videos\youtube-local-v2.5.8-windows\youtube-local\python\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Videos\youtube-local-v2.5.8-windows\youtube-local\python\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Videos\youtube-local-v2.5.8-windows\youtube-local\python\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Videos\youtube-local-v2.5.8-windows\youtube-local\python\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Videos\youtube-local-v2.5.8-windows\youtube-local\youtube\watch.py", line 372, in get_watch_page
    util.check_gevent_exceptions(tasks[1])
  File "D:\Videos\youtube-local-v2.5.8-windows\youtube-local\youtube\util.py", line 538, in check_gevent_exceptions
    raise task.exception
  File "src\\gevent\\greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "D:\Videos\youtube-local-v2.5.8-windows\youtube-local\youtube\watch.py", line 219, in extract_info
    debug_name='watch')
  File "D:\Videos\youtube-local-v2.5.8-windows\youtube-local\youtube\util.py", line 274, in fetch_url
    use_tor=use_tor)
  File "D:\Videos\youtube-local-v2.5.8-windows\youtube-local\youtube\util.py", line 260, in fetch_url_response
    decode_content=False, retries=retries)
  File "D:\Videos\youtube-local-v2.5.8-windows\youtube-local\python\lib\site-packages\urllib3\request.py", line 75, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "D:\Videos\youtube-local-v2.5.8-windows\youtube-local\python\lib\site-packages\urllib3\request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "D:\Videos\youtube-local-v2.5.8-windows\youtube-local\python\lib\site-packages\urllib3\poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "D:\Videos\youtube-local-v2.5.8-windows\youtube-local\python\lib\site-packages\urllib3\connectionpool.py", line 796, in urlopen
    **response_kw
  File "D:\Videos\youtube-local-v2.5.8-windows\youtube-local\python\lib\site-packages\urllib3\connectionpool.py", line 796, in urlopen
    **response_kw
  File "D:\Videos\youtube-local-v2.5.8-windows\youtube-local\python\lib\site-packages\urllib3\connectionpool.py", line 796, in urlopen
    **response_kw
  File "D:\Videos\youtube-local-v2.5.8-windows\youtube-local\python\lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "D:\Videos\youtube-local-v2.5.8-windows\youtube-local\python\lib\site-packages\urllib3\util\retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: SOCKSHTTPSConnectionPool(host='m.youtube.com', port=443): Max retries exceeded with url: /embed/-E_O2PwZpCc?bpctr=9999999999 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x04DABEF0>: Failed to establish a new connection: [Errno 10061] [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte.'))

Unsure what to do about it.

Greetings

**Comment by user234683** [comment]
The link is opened in the normal browser, not the Tor browser. However, the program needs Tor to be open. In fact, only Tor itself, tor.exe, is required, not the Tor Browser, but the Tor Browser is just a convenient way to launch it. I'll add instructions to the readme for how to configure bare-bones Tor so two browsers aren't required.
