### ISSUE TITLE
HTTP error during request: 404 Not Found

### ISSUE THREAD

**Issue by 89z** [user234683/youtube-local#72]
If I visit this page:

http://localhost:8080/https://www.youtube.com/watch?v=SkRSXFQerZs

I get this result:

~~~
Traceback (most recent call last):
  File "D:\Desktop\youtube-local\python\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Desktop\youtube-local\python\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Desktop\youtube-local\python\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Desktop\youtube-local\python\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Desktop\youtube-local\python\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Desktop\youtube-local\python\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Desktop\youtube-local\youtube\watch.py", line 372, in get_watch_page
    util.check_gevent_exceptions(tasks[1])
  File "D:\Desktop\youtube-local\youtube\util.py", line 538, in check_gevent_exceptions
    raise task.exception
  File "src\\gevent\\greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "D:\Desktop\youtube-local\youtube\watch.py", line 237, in extract_info
    report_text='Fetched get_video_info page').decode('utf-8')
  File "D:\Desktop\youtube-local\youtube\util.py", line 319, in fetch_url
    ip=None)
youtube.util.FetchError: HTTP error during request: 404 Not Found
~~~

**Comment by user234683** [comment]
Try the 2.6.0 release just posted

**Comment by 89z** [comment]
Thanks that did fix it, but now having trouble with another one:

http://localhost:8080/https://www.youtube.com/watch?v=Cr381pDsSsA

**Comment by arankaren** [comment]
> Thanks that did fix it, but now having trouble with another one:
> 
> http://localhost:8080/https://www.youtube.com/watch?v=Cr381pDsSsA

`Error: Error getting missing player or bypassing age-restriction: Playback on other websites has been disabled by the video owner.`

**Comment by 89z** [comment]
@arankaren OK, so how do I fix it?

**Comment by arankaren** [comment]
hmm, the **video require session login** :scream: 

 ```
Sign in to confirm your age
This video may be inappropriate for some users.
```

**Comment by user234683** [comment]
The problem is that the age-restriction bypass works by using the same requests that an embed page uses. However, that video has embedding disabled. This issue seems to also affect youtube-dl and invidious, so they don't seem to have figured out any workarounds. I haven't checked if NewPipe works though. If it does I can investigate how they do it. I'm trying to see if any `youtubei.googleapis.com` can work (see [here](https://github.com/TeamNewPipe/NewPipeExtractor/issues/562) ), but I haven't had luck with `ANDROID`, `ANDROID_EMBEDDED_PLAYER`, `WEB`, nor `MWEB`.

**Comment by 89z** [comment]
I think some videos only work with login, but if you find a way, let me know!

**Comment by 89z** [comment]
Looks like certain videos require authentication. I have a YouTube OAuth implementation here (in another language) if it helps:

https://github.com/89z/mech/blob/v1.20.3/youtube/oauth.go
