### ISSUE TITLE
Getting permission denied errors for /run/tor/control.authcookie

### ISSUE THREAD

**Issue by SlidingHorn** [user234683/youtube-local#73]
**EDIT 1:** As it turns out, there is *not* a new identity being acquired. I was seeing this on random auto-checks for subscriptions, whereas now I'm actually using the search feature, and catching this error, and the exit node is **not** changed.

---

**EDIT 2:** So I had my `CookieAuthentication` set to `1` instead of `0` in my `torrc` file. I believe this was the cause of my issue. I'm going to leave this open for a bit just to be sure that this was actually the root of the problem.

---

According to the log, it appears that there *is* a new identity acquired, but~~ there is a permissions error happening, and I don't know if it matters....

```
Error: Youtube blocked the request because the Tor exit node is overutilized. Exit node IP address: 89.163.154.91
new_identity: new_identity called
new_identity: New identity lock acquired
Traceback (most recent call last):
  File "/home/ryan/.local/lib/python3.8/site-packages/stem/connection.py", line 1103, in _read_cookie
    with open(cookie_path, 'rb', 0) as f:
PermissionError: [Errno 13] Permission denied: '/run/tor/control.authcookie'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/home/ryan/Downloads/youtube-local-2.5.8/youtube/channel.py", line 229, in get_channel_first_page
    return util.fetch_url(base_url + '/videos?pbj=1&view=0', headers_desktop,
  File "/home/ryan/Downloads/youtube-local-2.5.8/youtube/util.py", line 309, in fetch_url
    error = tor_manager.new_identity(start_time)
  File "/home/ryan/Downloads/youtube-local-2.5.8/youtube/util.py", line 130, in new_identity
    controller.authenticate('')
  File "/home/ryan/.local/lib/python3.8/site-packages/stem/control.py", line 1112, in authenticate
    stem.connection.authenticate(self, *args, **kwargs)
  File "/home/ryan/.local/lib/python3.8/site-packages/stem/connection.py", line 629, in authenticate
    raise auth_exc
  File "/home/ryan/.local/lib/python3.8/site-packages/stem/connection.py", line 591, in authenticate
    authenticate_safecookie(controller, cookie_path, False)
  File "/home/ryan/.local/lib/python3.8/site-packages/stem/connection.py", line 904, in authenticate_safecookie
    cookie_data = _read_cookie(cookie_path, True)
  File "/home/ryan/.local/lib/python3.8/site-packages/stem/connection.py", line 1107, in _read_cookie
    raise UnreadableCookieFile(exc_msg, cookie_path, is_safecookie)
stem.connection.UnreadableCookieFile: Authentication failed: unable to read '/run/tor/control.authcookie' ([Errno 13] Permission denied: '/run/tor/control.authcookie')
2021-07-22T03:09:42Z <Greenlet at 0x7fabcbe3bbf0: get_channel_first_page(channel_id='UCRE3NFNtdjR96-H4QG4U1Fg')> failed with UnreadableCookieFile
```

Again, I don't know if this matters if the new identity is created/acquired, but I figured I'd bring it up.

**Comment by user234683** [comment]
Yeah the new identity feature needs to access the Tor control port to tell Tor to get a new identity (which is done via stem). By default on linux, the control port requires authentication, but the default location it uses for its authentication file requires root permissions or a special user group to read it, so the quickest way is to just disable authentication, which should be fine as long as you have a working firewall.

Regular Tor routing uses the SOCKS port, so doesn't need the control port nor stem unless the exit node is blocked, in which case it will attempt to get a new identity using stem and the control port.

**Comment by SlidingHorn** [comment]
Haven't seen this since, so I'm going to go ahead and close this.
