### ISSUE TITLE
I have to run pip3 install -r requirements.txt more than once

### ISSUE THREAD

**Issue by airikr-e** [user234683/youtube-local#74]
Hi.

I downloaded the latest version (2.6.0) last night and extracted it to its own folder (`youtube-local-2.6.0`). After that, I created the `settings.txt` file to make it portable and ran `pip3 install -r requirements.txt`. After this, I ran `python3 server.py`. Everything worked. Perfect! I stopped the service and killed the port.

But after a good night of sleep, I ran `python3 server.py` again and got `sqlite3.OperationalError: unable to open database file` as an error. I ran `pip3 install -r requirements.txt` again and then `python3 server.py`. Worked perfectly.

So, now to my question. Why do I have to run `pip3 install -r requirements.txt` command more than once?

This issue were not present when I used an older version of youtube-local. I didn't use portable mode back then because it didn't work despite I had created the `settings.txt` file after I had used youtube-local a few times before (I suspect this has to be due to caching).

**Comment by user234683** [comment]
I suspect this is a problem with portable mode not working properly, rather than a dependency issue. If it was a missing dependency, you would likely get an ImportError, but it looks like it can't find the database file or isn't able to create it because the necessary data directory is failing to get created sometimes. Are you on Windows or Linux? And are you running from a flash drive, hard drive, or SSD?

**Comment by e-edgren** [comment]
Alright. I am using Linux and have the files on the local SSD.

**Comment by user234683** [comment]
Try a fresh installation, with a settings.txt file created to make it portable. Before running it, insert this between lines 31 and 32 in `./youtube/subscriptions.py` (right before the sqlite3 connection statement):
```
    print('Data directory exists:', os.path.isdir(settings.data_dir))
```
When you get the error, stop the program and restart it, to see if it works the second time or not. Then copy and paste the full console output from both attempts here, redacting as needed. My theory is that the `./data` directory where the database file needs to go isn't getting created in time for some reason.

**Comment by e-edgren** [comment]
I'm sorry, but that didn't work at all for me :/

I tried to add the line in the file that I normally use (somewhat fresh "install"). I got the error, but the new print I added into `subscriptions.py` didn't show at all.

So I downloaded the files from GitHub again, extracted the files to another destination, added the new line between lines 31 and 32, saved the file, and ran `python3 server.py` without running `pip3 install -r requirements.txt` first. Same there: it didn't show. Only this:

```
Running in portable mode
Tor routing is OFF - your Youtube activity is NOT anonymous
Traceback (most recent call last):
  File "/home/edgren/Documents/youtube-local-2.6.0/server.py", line 10, in <module>
    from youtube import watch, search, playlist, channel, local_playlist, comments, subscriptions
  File "/home/edgren/Documents/youtube-local-2.6.0/youtube/channel.py", line 2, in <module>
    from youtube import util, yt_data_extract, local_playlist, subscriptions
  File "/home/edgren/Documents/youtube-local-2.6.0/youtube/subscriptions.py", line 414, in <module>
    start_autocheck_system()
  File "/home/edgren/Documents/youtube-local-2.6.0/youtube/subscriptions.py", line 382, in start_autocheck_system
    with open_database() as connection:
  File "/home/edgren/Documents/youtube-local-2.6.0/youtube/subscriptions.py", line 32, in open_database
    connection = sqlite3.connect(database_path, check_same_thread=False)
sqlite3.OperationalError: unable to open database file
```

So unfortunately, I can't do anything about what you said :(

**Comment by user234683** [comment]
Are you sure you saved the file after adding the line, and are you running the installation where you added the line (rather than a different one)? Because the stack trace is showing the connection line as line 32, but it should be bumped up to line 33 if the print statement was inserted.

Also, check the permissions of the file ./data/subscriptions.db

**Comment by canjbfeeltheesemuffins** [comment]
virtualenv -p python3 venv

source venv/bin/activate

pip(3) install -r requirements.txt

**Comment by user234683** [comment]
Closing due to lack of activity
