### ISSUE TITLE
Playing video working fine but channel listing fails most of the time

### ISSUE THREAD

**Issue by Utopiah** [user234683/youtube-local#88]
I can watch https://www.youtube.com/watch?v=a-7lHqyBQeg no problem but if I try https://www.youtube.com/channel/UCarrX7HGvHP59-qttSKX8CQ I get : 

```
Traceback (most recent call last):
  File "/home/fabien/.local/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fabien/.local/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fabien/.local/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fabien/.local/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/fabien/Prototypes/youtube-local/youtube/channel.py", line 315, in get_channel_page
    return get_channel_page_general_url('https://www.youtube.com/channel/' + channel_id, tab, request, channel_id)
  File "/home/fabien/Prototypes/youtube-local/youtube/channel.py", line 271, in get_channel_page_general_url
    util.check_gevent_exceptions(*tasks)
  File "/home/fabien/Prototypes/youtube-local/youtube/util.py", line 590, in check_gevent_exceptions
    raise task.exception
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/home/fabien/.local/lib/python3.9/site-packages/cachetools/func.py", line 66, in wrapper
    v = func(*args, **kwargs)
  File "/home/fabien/Prototypes/youtube-local/youtube/channel.py", line 156, in get_number_of_videos_channel
    response = util.fetch_url(url, headers_mobile,
  File "/home/fabien/Prototypes/youtube-local/youtube/util.py", line 352, in fetch_url
    print(report_text, '    Latency:', round(response_time - start_time,3), '    Read time:', round(read_finish - response_time,3))
OSError: [Errno 5] Input/output error
```

using the current version from Github.

**Comment by user234683** [comment]
What OS and environment is it running in? It looks like the print statement has nowhere to go so it's failing. Is this being run in a cron job or similar where there's no stdout attached?

**Comment by Utopiah** [comment]
cron job using Python 3.9.5 on Ubuntu 21.04

I started it with stdout ... and (of course) can't reproduce it right despite opening a dozen of channels. I can try logging from cron if it helps.

**Comment by user234683** [comment]
It likely doesn't have anything to do with channels specifically, since that print statement is for any network request. I think it's just that python buffers the bytes that are pending to be written to stdout if stdout isn't accessible. Once that buffer gets full, it throws an error. So by piping stdout to /dev/null, it fixes the issue.

**Comment by user234683** [comment]
Another thing that might cause trouble is stderr, which should also be redirected to /dev/null. On second thought, from what I'm reading, cron will send an email if a process has any output, so it's still weird that stdout would fail.

**Comment by Utopiah** [comment]
I`ll try `python3 ~/Prototypes/youtube-local/server.py 2> /dev/null` then and if everything works for few days I'll close this after, if you want, modifying the readme to suggest it.

**Comment by user234683** [comment]
You might want to use `> /dev/null 2>&1` to redirect both of them. I think that command only redirects stderr
